# Generated by Django 3.0.4 on 2020-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
