# Generated by Django 3.0.4 on 2020-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_book_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Libro existente/No existente'),
        ),
    ]
